# Generated by Django 4.1 on 2022-09-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppThatBeer', '0005_alter_cliente_dni_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('subtitulo', models.CharField(max_length=35)),
                ('cuerpo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=25)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
