# Generated by Django 4.1 on 2022-09-16 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppThatBeer', '0007_alter_noticia_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fecha_posteo',
            field=models.DateField(default=datetime.datetime(2022, 9, 15, 23, 21, 34, 987176)),
        ),
    ]
