# Generated by Django 4.1.1 on 2022-09-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppThatBeer', '0010_alter_noticia_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticiasimg'),
        ),
    ]
