# Generated by Django 4.1.1 on 2022-09-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppThatBeer', '0011_alter_noticia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=models.CharField(default='Asd', max_length=3000),
            preserve_default=False,
        ),
    ]
