# Generated by Django 4.1.1 on 2022-09-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppThatBeer', '0012_alter_noticia_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha_posteo',
            field=models.CharField(max_length=10),
        ),
    ]
