# Generated by Django 4.1.1 on 2022-09-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppThatBeer', '0013_alter_noticia_fecha_posteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribuidor',
            name='cuit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha_posteo',
            field=models.DateField(),
        ),
    ]
