# Generated by Django 4.1.1 on 2022-09-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppThatBeer', '0015_alter_noticia_cuerpo_alter_noticia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=models.CharField(max_length=3000),
        ),
    ]
