# Generated by Django 4.1.1 on 2022-09-21 00:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppThatBeer', '0016_alter_noticia_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
