# Generated by Django 4.1.1 on 2022-09-21 18:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mensajes', '0002_alter_canalmensaje_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1500)),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('room', models.CharField(max_length=1500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='canalmensaje',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='canalmensaje',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='canalusuario',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='canalusuario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Canal',
        ),
        migrations.DeleteModel(
            name='CanalMensaje',
        ),
        migrations.DeleteModel(
            name='CanalUsuario',
        ),
    ]
