# Generated by Django 4.1.1 on 2022-09-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0003_message_room_remove_canalmensaje_canal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=15),
        ),
    ]
